/**
 * Amitha_Murali, 001643826, murali.a@husky.neu.edu
 * Jyoti Sharma, 001643410, sharma.j@husky.neu.edu
 * Surabhi Patil, 001251860, patil.sur@husky.neu.edu
 **/

package com.csye6225.demo.helpers;

import com.csye6225.demo.dao.UserRepository;
import com.csye6225.demo.entities.User;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.security.crypto.bcrypt.BCryptPasswordEncoder;
import org.springframework.stereotype.Service;

@Service
public class Helper {

    @Autowired
    private BCryptPasswordEncoder bCryptPasswordEncoder;

    @Autowired
    // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private UserRepository userRepository;


    public User validateUserEmail(String email)
    {
        for(User user:userRepository.findAll())
        {
            if(user.getEmail().equals(email))
                return user;

        }
        return null;
    }



    public User validateUser(String email, String password)
    {
        for(User user:userRepository.findAll())
        {
            if((user.getEmail().equals(email)) && (bCryptPasswordEncoder.matches(password,user.getPassword())|| user.getPassword().equals(password)) )
                return user;

        }
        return null;
    }


}
