/**
 * Amitha_Murali, 001643826, murali.a@husky.neu.edu
 * Jyoti Sharma, 001643410, sharma.j@husky.neu.edu
 * Surabhi Patil, 001251860, patil.sur@husky.neu.edu
 **/

package com.csye6225.demo.controllers;

import com.csye6225.demo.dao.FileAttachmentRepository;
import com.csye6225.demo.entities.Task;
import com.google.gson.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletRequest;
import javax.websocket.server.PathParam;

@Controller    // This means that this class is a Controller

public class FileAttachmentController {

    @Autowired
    // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private FileAttachmentRepository fileAttachmentRepository;

    @RequestMapping(value="/tasks/{id}/attachments",method= RequestMethod.GET,produces="application/json")
    public @ResponseBody String getAttachedFilesForTask (HttpServletRequest request){

        JsonObject jsonObject = new JsonObject();

        //Write add file code here

        jsonObject.addProperty("message", "sample.");
        return jsonObject.toString();

    }

    @RequestMapping(value="/tasks/{id}/attachments",method= RequestMethod.POST,produces="application/json")
    public @ResponseBody String attachFileToTask (HttpServletRequest request){

        JsonObject jsonObject = new JsonObject();

        //Write add file code here

        jsonObject.addProperty("message", "sample.");
        return jsonObject.toString();

    }

    @RequestMapping(value="/tasks/{id}/attachments/{idAttachments}",method= RequestMethod.DELETE,produces="application/json")
    public @ResponseBody String deleteFile (@PathParam("id")String id) {

        JsonObject jsonObject = new JsonObject();

        //Write delete file code here

        jsonObject.addProperty("message", "sample.");
        return jsonObject.toString();

    }

}
