/**
 * Amitha_Murali, 001643826, murali.a@husky.neu.edu
 * Jyoti Sharma, 001643410, sharma.j@husky.neu.edu
 * Surabhi Patil, 001251860, patil.sur@husky.neu.edu
 **/
package com.csye6225.demo.controllers;


import com.csye6225.demo.Helper;
import com.csye6225.demo.UserRepository;
import com.google.gson.JsonObject;

import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
<<<<<<< HEAD
<<<<<<< HEAD
=======
import org.springframework.http.HttpRequest;
>>>>>>> upstream/master
=======

>>>>>>> 146dc1cef02c29a0c0e32f34331f296f81540df4
import org.springframework.security.authentication.AnonymousAuthenticationToken;
import org.springframework.security.core.Authentication;
import org.springframework.security.core.context.SecurityContextHolder;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;
import com.csye6225.demo.User;
import java.util.Date;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import java.util.Base64;

@Controller
public class HomeController {


  @Autowired
  // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
  private UserRepository userRepository;

  @Autowired
  private Helper helper;

  private final static Logger logger = LoggerFactory.getLogger(HomeController.class);

  @RequestMapping(value = "/", method = RequestMethod.GET, produces = "application/json")
  @ResponseBody
  public String welcome(HttpServletRequest request, HttpServletResponse response) {

    JsonObject jsonObject = new JsonObject();

<<<<<<< HEAD

    /*
    //will contain "Basic Ym9iOnNlY3JldA=="
    String header = request.getHeader("Authorization");
    //always wise to assert your assumptions
    assert header.substring(0, 6).equals("Basic ");
    //will contain "Ym9iOnNlY3JldA=="
    String basicAuthEncoded = header.substring(6);
    //will contain "bob:secret"
    String basicAuthAsString = new String(
        new Base64().decode(basicAuthEncoded.getBytes()));
     */

    //if (SecurityContextHolder.getContext().getAuthentication() != null
       // && SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)

    Authentication auth = SecurityContextHolder.getContext().getAuthentication();
    String header = request.getHeader("Authorization");
    assert header.substring(0, 6).equals("Basic ");
    String basicAuthEncoded = header.substring(6);
    String basicAuthAsString = new String(Base64.getDecoder().decode(basicAuthEncoded.getBytes()));

    if(auth != null) {
    //final String[]  credentialValues = auth.getCredentials().toString().split(":",2);
      final String[]  credentialValues = basicAuthAsString.split(":",2);
    User user  = helper.validateUser(auth.getName(),credentialValues[1]);
    if(user == null){
      jsonObject.addProperty("message", "Invalid credentials.");
    } else {
      jsonObject.addProperty("message", "Hi, you have been successfully logged in. current time is " + new Date().toString());
=======
    //if (SecurityContextHolder.getContext().getAuthentication() != null && SecurityContextHolder.getContext().getAuthentication() instanceof AnonymousAuthenticationToken)

   Authentication auth = SecurityContextHolder.getContext().getAuthentication();


  //if(!(auth instanceof AnonymousAuthenticationToken)) {

    //This is the logic to fetch user password from the authorization header value by removing "Basic" keyword, decoding and splitting with :
       String header = request.getHeader("Authorization");
       if(header !=null && header.contains("Basic"))
       {
       assert header.substring(0, 6).equals("Basic");
       String basicAuthEncoded = header.substring(6);
       String basicAuthAsString = new String(Base64.getDecoder().decode(basicAuthEncoded.getBytes()));


      final String[] credentialValues = basicAuthAsString.split(":", 2);
      //If user exists in DB , return the user object.
      User user = helper.validateUser(credentialValues[0], credentialValues[1]);

      if (user == null) {
        jsonObject.addProperty("message", "Invalid credentials.Try again!!!");
      } else {
        jsonObject.addProperty("message", "Hi, you have been successfully logged in. current time is " + new Date().toString());
      }
>>>>>>> upstream/master
    }
    }
    jsonObject.addProperty("message", "You are not logged in!!!");

   else
   {
        jsonObject.addProperty("message", "You are not logged in!!!");
   }

    return jsonObject.toString();

 /*String auth = request.getHeader("Authorization");
 if(auth!=null && auth.startsWith("Basic"))
 {
     String header = request.getHeader("Authorization");
     assert header.substring(0, 6).equals("Basic ");
     String basicAuthEncoded = header.substring(6);
     String basicAuthAsString = new String(Base64.getDecoder().decode(basicAuthEncoded.getBytes()));
     final String[] credentialValues = basicAuthAsString.split(":", 2);
     //If user exists in DB , return the user object.
     User user = helper.validateUser(credentialValues[0], credentialValues[1]);

     if(user!= null) {
         jsonObject.addProperty("message", "Hi, you have been successfully logged in. current time is " + new Date().toString());
     }
     else {
         jsonObject.addProperty("message", "You are not logged in!!!");
     }

 }
 else
 {
     jsonObject.addProperty("message", "You are not logged in!!!");
 }

 return jsonObject.toString();*/
  }

  @RequestMapping(value = "/test", method = RequestMethod.GET, produces = "application/json")
  @ResponseBody
  public String test() {
    JsonObject jsonObject = new JsonObject();
    jsonObject.addProperty("message", "authorized for /test");
    return jsonObject.toString();
  }

  @RequestMapping(value = "/testPost", method = RequestMethod.POST, produces = "application/json")
  @ResponseBody
  public String testPost() {
    JsonObject jsonObject = new JsonObject();
    jsonObject.addProperty("message", "authorized for /testPost");
    return jsonObject.toString();
  }

}
