package com.csye6225.demo.controllers;

import com.csye6225.demo.*;
import com.google.gson.JsonObject;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestMethod;
import org.springframework.web.bind.annotation.ResponseBody;

import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;
import javax.servlet.http.HttpSession;

@Controller
public class UserTaskController {

    @Autowired
    // This means to get the bean called userRepository which is auto-generated by Spring, we will use it to handle the data
    private TaskRepository taskRepository;

    @RequestMapping(value = "/tasks", method = RequestMethod.POST, produces = "application/json")
    @ResponseBody
    public String userTask(HttpServletRequest request, HttpServletResponse response) {

        String taskDescription = request.getParameter("description");
        HttpSession session = request.getSession();
        if(session != null) {

            //UserModel user = (UserModel) session.getAttribute( "user" );

            //if(user !=null) {

                Task userTask = new Task();
                userTask.setUuid();
                userTask.setUserId( 1 );
                userTask.setDescription( taskDescription );
                taskRepository.save( userTask );

                JsonObject jsonObject = new JsonObject();
                jsonObject.addProperty( "message", "Task has been created successfully for the User." );
                jsonObject.addProperty( "userId", userTask.getUserId() );
                jsonObject.addProperty( "taskUuid", userTask.getUuid().toString() );
                jsonObject.addProperty( "taskDescription", userTask.getDescription() );
                return jsonObject.toString();
            //}
        }

        JsonObject jsonObject = new JsonObject();
        jsonObject.addProperty("message", "Session not found! Please login again.");
        return jsonObject.toString();
    }

}
